version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    networks:
      - app-net
  app:
    build: .
    ports:
      - 1323:1323
    environment:
      SERVER_PORT: 1323
    depends_on:
      - redis
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - app-net
volumes:
  redisdata:
    driver: local
networks:
  app-net:
    driver: bridge